<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Inputs" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-01-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SPLIT_BYTE_INTO_BOOLS" Type="SPLIT_BYTE_INTO_BOOLS" x="2346.67" y="3760">
		</FB>
		<FB Name="Inputs" Type="CLIENT_0_1" x="413.33" y="3460">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_02_TCP"/>
		</FB>
		<FB Name="DigitalOutput_Q1" Type="QX" x="6860" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q1" Type="E_D_FF" x="5200" y="300">
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q2" Type="E_D_FF" x="5200" y="1380">
		</FB>
		<FB Name="DigitalOutput_Q2" Type="QX" x="6860" y="1180">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q3" Type="E_D_FF" x="5200" y="2460">
		</FB>
		<FB Name="DigitalOutput_Q3" Type="QX" x="6860" y="2260">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q4" Type="E_D_FF" x="5266.67" y="3540">
		</FB>
		<FB Name="DigitalOutput_Q4" Type="QX" x="6926.67" y="3340">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q5" Type="E_D_FF" x="5200" y="4620">
		</FB>
		<FB Name="DigitalOutput_Q5" Type="QX" x="6860" y="4420">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q6" Type="E_D_FF" x="5200" y="5700">
		</FB>
		<FB Name="DigitalOutput_Q6" Type="QX" x="6860" y="5500">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q7" Type="E_D_FF" x="5200" y="6780">
		</FB>
		<FB Name="DigitalOutput_Q7" Type="QX" x="6860" y="6580">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_D_FF_DigitalOutput_Q8" Type="E_D_FF" x="5200" y="7860">
		</FB>
		<FB Name="DigitalOutput_Q8" Type="QX" x="6860" y="7660">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="EI_TO_E" Type="EI_TO_E" x="-700" y="3600">
		</FB>
		<EventConnections>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q1.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q1.EO" Destination="DigitalOutput_Q1.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q2.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q2.EO" Destination="DigitalOutput_Q2.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q3.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q3.EO" Destination="DigitalOutput_Q3.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q4.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q4.EO" Destination="DigitalOutput_Q4.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q5.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q5.EO" Destination="DigitalOutput_Q5.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q6.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q6.EO" Destination="DigitalOutput_Q6.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q7.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q7.EO" Destination="DigitalOutput_Q7.REQ" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="E_D_FF_DigitalOutput_Q8.CLK" dx1="340">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_D_FF_DigitalOutput_Q8.EO" Destination="DigitalOutput_Q8.REQ" dx1="73.33"/>
			<Connection Source="Inputs.INITO" Destination="EI_TO_E.IN" dx1="80" dx2="80" dy="-813.33"/>
			<Connection Source="EI_TO_E.OUT" Destination="Inputs.REQ" dx1="253.33"/>
			<Connection Source="Inputs.CNF" Destination="SPLIT_BYTE_INTO_BOOLS.REQ" dx1="593.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_D_FF_DigitalOutput_Q1.Q" Destination="DigitalOutput_Q1.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q2.Q" Destination="DigitalOutput_Q2.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q3.Q" Destination="DigitalOutput_Q3.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q4.Q" Destination="DigitalOutput_Q4.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q5.Q" Destination="DigitalOutput_Q5.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q6.Q" Destination="DigitalOutput_Q6.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q7.Q" Destination="DigitalOutput_Q7.OUT" dx1="73.33"/>
			<Connection Source="E_D_FF_DigitalOutput_Q8.Q" Destination="DigitalOutput_Q8.OUT" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_00" Destination="E_D_FF_DigitalOutput_Q1.D" dx1="73.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_01" Destination="E_D_FF_DigitalOutput_Q2.D" dx1="140"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_02" Destination="E_D_FF_DigitalOutput_Q3.D" dx1="206.67"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_03" Destination="E_D_FF_DigitalOutput_Q4.D" dx1="406.67"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_04" Destination="E_D_FF_DigitalOutput_Q5.D" dx1="273.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_05" Destination="E_D_FF_DigitalOutput_Q6.D" dx1="206.67"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_06" Destination="E_D_FF_DigitalOutput_Q7.D" dx1="140"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_07" Destination="E_D_FF_DigitalOutput_Q8.D" dx1="73.33"/>
			<Connection Source="Inputs.RD_1" Destination="SPLIT_BYTE_INTO_BOOLS.IN" dx1="513.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
