<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Inputs" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-01-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SPLIT_BYTE_INTO_BOOLS" Type="SPLIT_BYTE_INTO_BOOLS" x="2300" y="3800">
		</FB>
		<FB Name="Inputs" Type="CLIENT_0_1" x="400" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_02_TCP"/>
		</FB>
		<FB Name="EI_TO_E" Type="EI_TO_E" x="-700" y="3600">
		</FB>
		<FB Name="CLIENT_8" Type="CLIENT_8" x="4900" y="3500">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_01_RTU"/>
		</FB>
		<EventConnections>
			<Connection Source="Inputs.INITO" Destination="EI_TO_E.IN" dx1="80" dx2="80" dy="-813.33"/>
			<Connection Source="EI_TO_E.OUT" Destination="Inputs.REQ"/>
			<Connection Source="Inputs.CNF" Destination="SPLIT_BYTE_INTO_BOOLS.REQ" dx1="593.33"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.CNF" Destination="CLIENT_8.REQ" dx1="780"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Inputs.RD_1" Destination="SPLIT_BYTE_INTO_BOOLS.IN"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_00" Destination="CLIENT_8.SD_1"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_01" Destination="CLIENT_8.SD_2"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_02" Destination="CLIENT_8.SD_3"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_03" Destination="CLIENT_8.SD_4"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_04" Destination="CLIENT_8.SD_5"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_05" Destination="CLIENT_8.SD_6"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_06" Destination="CLIENT_8.SD_7"/>
			<Connection Source="SPLIT_BYTE_INTO_BOOLS.BIT_07" Destination="CLIENT_8.SD_8"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
