<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="modbus_rtu" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-01-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="CLIENT_8" Type="CLIENT_8" x="1586.67" y="353.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_01_RTU"/>
			<Parameter Name="SD_1" Value="BYTE#16#1"/>
			<Parameter Name="SD_2" Value="BYTE#16#0"/>
			<Parameter Name="SD_3" Value="BYTE#16#1"/>
			<Parameter Name="SD_4" Value="BYTE#16#0"/>
			<Parameter Name="SD_5" Value="BYTE#16#1"/>
			<Parameter Name="SD_6" Value="BYTE#16#0"/>
			<Parameter Name="SD_7" Value="BYTE#16#1"/>
			<Parameter Name="SD_8" Value="BYTE#16#0"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
