<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Outputs" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-01-31">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="F_BYTE_TO_WORD" Type="F_BYTE_TO_WORD" x="3400" y="4300">
		</FB>
		<FB Name="ASSEMBLE_BYTE_FROM_BOOLS" Type="ASSEMBLE_BYTE_FROM_BOOLS" x="1600" y="4300">
		</FB>
		<FB Name="Outputs" Type="CLIENT_1" x="4900" y="4200">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="ID_01_TCP"/>
		</FB>
		<FB Name="SPLIT_BYTE_INTO_BOOLS" Type="SPLIT_BYTE_INTO_BOOLS" x="6000" y="4300">
		</FB>
		<FB Name="CLIENT_0_8" Type="CLIENT_0_8" x="-300" y="4000">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="ID" Value="modbus_const::ID_02_RTU"/>
		</FB>
		<FB Name="EI_TO_E" Type="EI_TO_E" x="-1400" y="4100">
		</FB>
		<EventConnections>
			<Connection Source="ASSEMBLE_BYTE_FROM_BOOLS.CNF" Destination="F_BYTE_TO_WORD.REQ"/>
			<Connection Source="F_BYTE_TO_WORD.CNF" Destination="Outputs.REQ"/>
			<Connection Source="Outputs.CNF" Destination="SPLIT_BYTE_INTO_BOOLS.REQ"/>
			<Connection Source="EI_TO_E.OUT" Destination="CLIENT_0_8.REQ" dx1="246.67"/>
			<Connection Source="CLIENT_0_8.INITO" Destination="EI_TO_E.IN" dx1="80" dx2="80" dy="-426.67"/>
			<Connection Source="CLIENT_0_8.CNF" Destination="ASSEMBLE_BYTE_FROM_BOOLS.REQ" dx1="613.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="ASSEMBLE_BYTE_FROM_BOOLS." Destination="F_BYTE_TO_WORD.IN"/>
			<Connection Source="F_BYTE_TO_WORD.OUT" Destination="Outputs.SD_1" dx1="73.33"/>
			<Connection Source="Outputs.RD_1" Destination="SPLIT_BYTE_INTO_BOOLS.IN" dx1="73.33"/>
			<Connection Source="CLIENT_0_8.RD_1" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_00" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_2" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_01" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_3" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_02" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_4" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_03" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_5" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_04" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_6" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_05" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_7" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_06" dx1="520"/>
			<Connection Source="CLIENT_0_8.RD_8" Destination="ASSEMBLE_BYTE_FROM_BOOLS.BIT_07" dx1="520"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
